[package]
name = "csqrl/codify-plugin"
version = "3.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
Highlighter = "boatbomber/highlighter@0.7.0"
Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.5"
